on:
  push: 
    branches:
      - develop
name: 🚀 Deploy website to Develop
jobs:
  web-deploy:
    name: 🎉 Develop Branch
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.didgenation.com
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        local-dir: ./themes/mytheme/
        server-dir : develop.didgenation.com/portal/themes/mytheme/
